#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if [ ! $(command -v gometalinter) ]; then
	go get -u github.com/alecthomas/gometalinter
	gometalinter --update --install
fi

for d in $(find . -type d -not -iwholename '*.git*' -a -not -iname '.tool' -a -not -iwholename '*vendor*'); do
	gometalinter \
		--exclude='error return value not checked.*(Close|Log|Print).*\(errcheck\)$' \
		--exclude='.*_test\.go:.*error return value not checked.*\(errcheck\)$' \
		--exclude='duplicate of.*_test.go.*\(dupl\)$' \
		--exclude='^cmd/oci-image-tool/cas_get.go:.* duplicate of .* \(dupl\)$' \
		--exclude='^cmd/oci-image-tool/cas_put.go:.* duplicate of .* \(dupl\)$' \
		--exclude='^cmd/oci-image-tool/refs_get.go:.* duplicate of .* \(dupl\)$' \
		--exclude='^cmd/oci-image-tool/refs_list.go:.* duplicate of .* \(dupl\)$' \
		--exclude='^cmd/oci-image-tool/refs_put.go:.* duplicate of .* \(dupl\)$' \
		--exclude='schema/fs.go' \
		--disable=aligncheck \
		--disable=gotype \
		--disable=gas \
		--cyclo-over=35 \
		--tests \
		--deadline=10s "${d}"
done
