package validation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Validate validates this ID mapping
func (m *IDMapping) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContainerID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateHostID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSize(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IDMapping) validateContainerID(formats strfmt.Registry) error {

	if swag.IsZero(m.ContainerID) { // not required
		return nil
	}

	if err := m.ContainerID.Validate(formats); err != nil {
		return err
	}

	return nil
}

func (m *IDMapping) validateHostID(formats strfmt.Registry) error {

	if swag.IsZero(m.HostID) { // not required
		return nil
	}

	if err := m.HostID.Validate(formats); err != nil {
		return err
	}

	return nil
}

func (m *IDMapping) validateSize(formats strfmt.Registry) error {

	if swag.IsZero(m.Size) { // not required
		return nil
	}

	if err := m.Size.Validate(formats); err != nil {
		return err
	}

	return nil
}
