package validation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Validate validates this rootfs
func (m *Rootfs) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDiffIds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Rootfs) validateDiffIds(formats strfmt.Registry) error {

	if swag.IsZero(m.DiffIds) { // not required
		return nil
	}

	return nil
}
