package validation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Validate validates this string pointer
func (m StringPointer) Validate(formats strfmt.Registry) error {
	return nil
}
