package validation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Validate validates this uint64 pointer
func (m *Uint64Pointer) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.Uint64.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
