package specs-go

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command




/*Annotations annotations

swagger:model annotations
*/
type Annotations struct {
  
  
  MapStringString
  
  
  
  
}




