package specs-go

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
  strfmt "github.com/go-openapi/strfmt"

  "github.com/go-openapi/errors"
  "github.com/go-openapi/runtime"
  "github.com/go-openapi/validate"
  
  
)



/*Config config

swagger:model config
*/
type Config struct {
  
  
  /* cmd
 */
Cmd []string `json:"Cmd,omitempty"`

  
  /* Cpu shares
 */
CPUShares Int64 `json:"CpuShares,omitempty"`

  
  /* entrypoint
 */
Entrypoint []string `json:"Entrypoint,omitempty"`

  
  /* env
 */
Env []string `json:"Env,omitempty"`

  
  /* exposed ports
 */
ExposedPorts MapStringObject `json:"ExposedPorts,omitempty"`

  
  /* memory
 */
Memory Int64 `json:"Memory,omitempty"`

  
  /* memory swap
 */
MemorySwap Int64 `json:"MemorySwap,omitempty"`

  
  /* user
 */
User string `json:"User,omitempty"`

  
  /* volumes
 */
Volumes MapStringObject `json:"Volumes,omitempty"`

  
  /* working dir
 */
WorkingDir string `json:"WorkingDir,omitempty"`

  
  
  
}




