package specs-go

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
  strfmt "github.com/go-openapi/strfmt"

  "github.com/go-openapi/errors"
  "github.com/go-openapi/runtime"
  "github.com/go-openapi/validate"
  
  
)



/*Digest the cryptographic checksum digest of the object, in the pattern '<hash>:<hexadecimal digest>'

swagger:model digest
*/
type Digest string




