package specs-go

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command




/*Env env

swagger:model Env
*/
type Env struct {
  
  
  ArrayOfStrings
  
  
  
  
}




