package specs-go

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
  strfmt "github.com/go-openapi/strfmt"

  "github.com/go-openapi/errors"
  "github.com/go-openapi/runtime"
  "github.com/go-openapi/validate"
  
  
)



/*History history

swagger:model history
*/
type History struct {
  
  
  /* author
 */
Author string `json:"author,omitempty"`

  
  /* comment
 */
Comment string `json:"comment,omitempty"`

  
  /* created
 */
Created strfmt.DateTime `json:"created,omitempty"`

  
  /* created by
 */
CreatedBy string `json:"created_by,omitempty"`

  
  /* empty layer
 */
EmptyLayer bool `json:"empty_layer,omitempty"`

  
  
  
}




