package specs-go

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
  strfmt "github.com/go-openapi/strfmt"

  "github.com/go-openapi/errors"
  "github.com/go-openapi/runtime"
  "github.com/go-openapi/validate"
  
  
)



/*Hook hook

swagger:model Hook
*/
type Hook struct {
  
  
  /* args
 */
Args ArrayOfStrings `json:"args,omitempty"`

  
  /* env
 */
Env Env `json:"env,omitempty"`

  
  /* path
 */
Path FilePath `json:"path,omitempty"`

  
  
  
}




