package specs-go

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
  strfmt "github.com/go-openapi/strfmt"

  "github.com/go-openapi/errors"
  "github.com/go-openapi/runtime"
  "github.com/go-openapi/validate"
  
  
)



/*IDMapping ID mapping

swagger:model IDMapping
*/
type IDMapping struct {
  
  
  /* container ID
 */
ContainerID Uint32 `json:"containerID,omitempty"`

  
  /* host ID
 */
HostID Uint32 `json:"hostID,omitempty"`

  
  /* size
 */
Size Uint32 `json:"size,omitempty"`

  
  
  
}




