package specs-go

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
  strfmt "github.com/go-openapi/strfmt"

  "github.com/go-openapi/errors"
  "github.com/go-openapi/runtime"
  "github.com/go-openapi/validate"
  
  
)



/*ManifestDescriptor manifest descriptor

swagger:model manifestDescriptor
*/
type ManifestDescriptor struct {
  
  
  /* digest

Required: true
 */
Digest Digest `json:"digest"`

  
  /* the mediatype of the referenced object

Required: true
 */
MediaType MediaType `json:"mediaType"`

  
  /* platform

Required: true
 */
Platform *ManifestDescriptorPlatform `json:"platform"`

  
  /* the size in bytes of the referenced object

Required: true
 */
Size *int64 `json:"size"`

  
  
  
}




/*ManifestDescriptorPlatform manifest descriptor platform

swagger:model ManifestDescriptorPlatform
*/
type ManifestDescriptorPlatform struct {
  
  
  /* architecture

Required: true
 */
Architecture *string `json:"architecture"`

  
  /* features
 */
Features []string `json:"features,omitempty"`

  
  /* os

Required: true
 */
Os *string `json:"os"`

  
  /* os features
 */
OsFeatures []string `json:"os.features,omitempty"`

  
  /* os version
 */
OsVersion string `json:"os.version,omitempty"`

  
  /* variant
 */
Variant string `json:"variant,omitempty"`

  
  
  
}



