package specs-go

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
  strfmt "github.com/go-openapi/strfmt"

  "github.com/go-openapi/errors"
  "github.com/go-openapi/runtime"
  "github.com/go-openapi/validate"
  
  
)



/*Mount mount

swagger:model Mount
*/
type Mount struct {
  
  
  /* destination

Required: true
 */
Destination FilePath `json:"destination"`

  
  /* options
 */
Options ArrayOfStrings `json:"options,omitempty"`

  
  /* source

Required: true
 */
Source FilePath `json:"source"`

  
  /* type

Required: true
 */
Type *string `json:"type"`

  
  
  
}




