package specs-go

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
  strfmt "github.com/go-openapi/strfmt"

  "github.com/go-openapi/errors"
  "github.com/go-openapi/runtime"
  "github.com/go-openapi/validate"
  
  
)



/*Rootfs rootfs

swagger:model rootfs
*/
type Rootfs struct {
  
  
  /* diff ids
 */
DiffIds []string `json:"diff_ids,omitempty"`

  
  /* layers
 */
Layers string `json:"layers,omitempty"`

  
  
  
}




