package specs-go

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command




/*Uint64Pointer uint64 pointer

swagger:model uint64Pointer
*/
type Uint64Pointer struct {
  
  
  Uint64
  
  
  
  
}




