package specs-go

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command




/*Uint16Pointer uint16 pointer

swagger:model uint16Pointer
*/
type Uint16Pointer struct {
  
  
  Uint16
  
  
  
  
}




